services:
  flask_app:
    build: .
    image: final_cpp_real_estate-flask_app  
    ports:
      - "8080:8080"
    env_file:
      - .env  # Ensure this line is present if you're using a .env file
    
